export enum PaymentStatus {
	INITIATED = 'INITIATED',
	CHECKOUT_CREATED = 'CHECKOUT_CREATED',
	AWAITING_WEBHOOK = 'AWAITING_WEBHOOK',
	SUCCEEDED = 'SUCCEEDED',
	FAILED = 'FAILED',
	CANCELED = 'CANCELED',
	EXPIRED = 'EXPIRED',
	REFUND_PENDING = 'REFUND_PENDING',
	REFUNDED = 'REFUNDED',
}
