export enum ReservationStatus  {
    PENDING_VALIDATION = 'PENDING_VALIDATION',
    VALIDATION_APPROVED = 'VALIDATION_APPROVED',
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',
    FAILED = 'FAILED',
    EXPIRED = 'EXPIRED',
    CONFIRMED = 'CONFIRMED',
    CANCELLED = 'CANCELLED',
    REFUND_PENDING = 'REFUND_PENDING',
    REFUNDED = 'REFUNDED',
}