syntax = "proto3";

package location;



service LocationService {
  rpc CreateLocation (CreateLocationRequest) returns (CreateLocationResponse);
  rpc UpdateLocation (UpdateLocationRequest) returns (UpdateLocationResponse);
}

message CreateLocationRequest {
  string ownerId = 1;
  string address = 2;
  string governorate = 3;
  double latitude = 4;
  double longitude = 5;
  string createdAt = 6; // ISO 8601 string
}

message CreateLocationResponse {
  bool success = 1;
  string error = 2;
}

message UpdateLocationRequest {
  string ownerId = 1;
  string address = 2; 
  string governorate = 3;
  double latitude = 4;
  double longitude = 5;
}

message UpdateLocationResponse {
  bool success = 1;
  optional string error = 2;
}
